### ISSUE TITLE
Calendar notifications unusable

### ISSUE THREAD

**Issue by goodwillcoding** [lvitals/panel-indicators#1]
Thank for this awesome extensions. Wanted to mention a bug.

When notifications are split from the calendar the calendar notifications which show as one navigates the calendar are unusable.

**Comment by lvitals** [comment]
Thanks for reporting this possible bug, I did all the testing with Gnome 3.34 and couldn't simulate issues with the notification.
What is your version of Gnome? What are the steps to reproduce the problem?

**Comment by goodwillcoding** [comment]
@lvitals my apologies for not beting more clear.

I am refering to the basic built in functionality of events showing on the calendar. Here is how to reproduce. 
1. Disable panel-indicator
2. Launch gnome-calendar and create coupdl of event for tomorrow
3. Click on date to open calendar
4. now click on the date for tomorro.

The events you created now show in the event list.

The issue is that the event list contains a section for calendar events and splitting the two up make is it impossible to navigate the calendar and see event other then today.

**Comment by lvitals** [comment]
> @lvitals my apologies for not beting more clear.
> 
> I am refering to the basic built in functionality of events showing on the calendar. Here is how to reproduce.
> 
> 1. Disable panel-indicator
> 2. Launch gnome-calendar and create coupdl of event for tomorrow
> 3. Click on date to open calendar
> 4. now click on the date for tomorro.
> 
> The events you created now show in the event list.
> 
> The issue is that the event list contains a section for calendar events and splitting the two up make is it impossible to navigate the calendar and see event other then today.

To resolve this issue, need to separate calendar events with notifications. I will be making this new behavior available. Thank you

**Comment by lvitals** [comment]
Resolved issue #069636e93d834150ebf95d6b41c465d3a8d71779

**Comment by lvitals** [comment]
Resolved issue https://github.com/lvitals/panel-indicators/commit/069636e93d834150ebf95d6b41c465d3a8d71779
