### ISSUE TITLE
Suggestion for translations

### ISSUE THREAD

**Issue by Etamuk** [lvitals/panel-indicators#5]
Hello :-) 

I just created the initial german translation for panel indicators. 
While working on it I noticed some strings are not translated because they are not listet in pot-file. Please see my both screenshots.

Another little suggestion is about the settings tab "Position and size". 
There are all the indicators listet. And every indicator has the ending "xyz-**indicator**".

What do you think about renaming it to the first word (without the ending _indicator_). For example:
_____________________
Indicators order

Calendar
Nightlight
Volume
Network
…
_____________________

It's just an suggestion. :-)

Best regards from germany 
and happy new year 
:fireworks: :fireworks: :fireworks: :fireworks: :fireworks: 

![Bildschirmfoto von 2020-01-01 13-50-19](https://user-images.githubusercontent.com/20098065/71641666-152ece80-2ca0-11ea-9506-adf4fbbf78a4.png)
![Bildschirmfoto von 2020-01-01 13-52-06](https://user-images.githubusercontent.com/20098065/71641667-152ece80-2ca0-11ea-83d1-f702c32013b1.png)

**Comment by lvitals** [comment]
Hello

Really appreciate the contribution.
Some strings are not translated because several changes have been made to code that does not accompany the translation. Your suggestion is welcome. I agree to remove the "xyz indicator" from the end, this is repetitive, could you make this change? Happy New Year. Obrigado ;-)

**Comment by Etamuk** [comment]
Hello

You have to know I am no programmer and so I don't know much about it ;-) 
When I try to change "calendar indicator" in pot file to "calendar" the the first entry in "settings -> change date format" is also without the ending -indicator. In this case on the first tab (settings) it should be further named "calendar indicator". Adding the missing strings for translating also exceeds my skills :-) 

But I am good in translating :-D

**Comment by lvitals** [comment]
@Etamuk Translation corrections done. Could you revise your translation? thanks
bcf6083859b9d267adcfe161d0a29771bfcaff05

**Comment by Etamuk** [comment]
Hello @lvitals 
I have updated my Pull Request with the latest changes for german translation. 
Best regards!

**Comment by lvitals** [comment]
Resolved issue bcf6083859b9d267adcfe161d0a29771bfcaff05
@Etamuk Thank you
