### ISSUE TITLE
Can you make the indicator sizes the same?

### ISSUE THREAD

**Issue by SaucySauce** [lvitals/panel-indicators#6]
Can the indicators all have the same "box" size in the status menu? User and Bluetooth have smaller "boxes".

**Comment by SaucySauce** [comment]
Extensions with indicators like "Extensions" and "Screenshot Tool" have the same "box" size (the area that can be clicked on)

**Comment by lvitals** [comment]
Hello, only the "User" and "Bluetooth" indicators are not from gnome-shell and are set to 16px size. I don't realize this size difference. Could you tell me what size is expected so that I can have a comparative?

**Comment by lvitals** [comment]
Hello, only the "User" and "Bluetooth" indicators are not from gnome-shell and are set to 16px size. I don't realize this size difference. Could you tell me what size is expected so that I can have a comparative?

**Comment by lvitals** [comment]
Icons need a padding 4px size.

**Comment by lvitals** [comment]
Done 55462a3734701535fa519d2eaee72b77f5421e75

**Comment by SaucySauce** [comment]
I'll need to check some other indicator extensions but it seems like a decent rule of thumb is the Pantheon Desktop status indicators trigger box size.

**Comment by SaucySauce** [comment]
Oh, I was writing as you updated. I'll check it out.

**Comment by SaucySauce** [comment]
Update the gnome extensions website.

**Comment by lvitals** [comment]
I already requested the update, but it will need to be audited by gnome maintainers

**Comment by SaucySauce** [comment]
Ok, so far with Adwaita it's perfect and with Adementary theme it's also perfect. The icons are evenly spaced as well as the action trigger boxes are evenly matched throughout the entire set of indicators. Nicely done.
