### ISSUE TITLE
Calendar moves back to center bug

### ISSUE THREAD

**Issue by SaucySauce** [lvitals/panel-indicators#7]
Every time there's a shell changing event like installing an extension that updates the top menu in any way, shape or form, the clock goes back to center even though the settings still specify that it's in the left position. Occasionally, locking the computer or suspending it will cause the bug to happen.

**Comment by lvitals** [comment]
Thanks for reporting this bug, the problem is happening, I will make the correction.

**Comment by lvitals** [comment]
Done, 569cfd658227545de98578a09ed84786eafc5d92

**Comment by SaucySauce** [comment]
Alright, so far so good. I haven't need to move it. I'll let you know how it goes in the next few hours.

**Comment by SaucySauce** [comment]
Few hours have passed, still nothing to report.
