### ISSUE TITLE
Bluetooth indicator doesn't have on off button

### ISSUE THREAD

**Issue by SaucySauce** [lvitals/panel-indicators#8]
When Bluetooth is active the indicator shows an option to turn it off but when it's off it only shows a shortcut to the Bluetooth Settings in the Settings app.
![Screenshot-20200114140724-1280x800](https://user-images.githubusercontent.com/38703177/72355552-38fa0780-36d7-11ea-83a5-9b6c8cbbacf1.png)

**Comment by lvitals** [comment]
I had already noticed this behavior, I need to resolve without breaking another extension I'm using for Bluetooth https://extensions.gnome.org/extension/1401/bluetooth-quick-connect/

**Comment by lvitals** [comment]
I could bring this same functionality to the extension, but I intend not to increase the complexity and solve certain problems with other extensions.

**Comment by SaucySauce** [comment]
Do you plan on adding some functionality or make existent extensions compatible with yours? Extensions that add extra buttons to the original status indicator menu could be easily added as extra functionality to your extension, i.e. Tweak settings shortcut under the System Settings in the user indicator. Btw, I tried that Bluetooth quick settings extension and it doesn't work.

**Comment by lvitals** [comment]
Weird. I have been using it without any problem, because the extension panel-indicators is not modified the elements that are in gnome-shell, just delocating and reodenating, just a few things are added. It is to be compatible with other extensions.

**Comment by lvitals** [comment]
I will get around this problem

**Comment by lvitals** [comment]
Done 0bc26d93bf817ee80da0d2e146acdbf77e5368a1

**Comment by SaucySauce** [comment]
Excellent.
