### ISSUE TITLE
Audio apps still show in audio indicator after they're closed

### ISSUE THREAD

**Issue by SaucySauce** [lvitals/panel-indicators#9]
Even after I close a once active audio based app like Shortwave or Lollypop it still shows in the sound indicator. 
![Screenshot-20200114160820-1280x800](https://user-images.githubusercontent.com/38703177/72365627-1c1a0000-36e8-11ea-9d3e-8df255e0b286.png)

**Comment by lvitals** [comment]
I see you are using a custom gnome-shell look. The behavior of the indicator is exactly that. It is a shortcut to open Lollypop or another audio player by the indicator, next to the icon has a close button. Your custom appearance of the gnome shell is distorting the icon. But I don't know if this functionality is very useful, maybe I will remove it.

**Comment by SaucySauce** [comment]
You can keep it but add a "Recent audio apps used" above the shortcuts. It should clear out any doubts.

**Comment by SaucySauce** [comment]
Also, Adwaita shows exactly like the Adementary theme, no distortion.

**Comment by lvitals** [comment]
This functionality causes other issues, such as removing the split line above "Volume Settings." It really is not very intuitive

**Comment by lvitals** [comment]
Sorry, You're right, the Adwaita theme is the same way. Unlike the theme Yaru.

**Comment by lvitals** [comment]
Things will be better without this functionality

**Comment by SaucySauce** [comment]
I only now noticed Adementary has a weird bug that makes the left side bezel of the playing audio app section really close to the menu border but the right side is ok. It's on the theme though as Adwaita shows perfectly. By the way, how do we know if the the extension on gnome extensions website has been updated? I keep getting "extension update available" whenever I open the browser.

**Comment by SaucySauce** [comment]
![Screenshot-20200115123621-1280x800](https://user-images.githubusercontent.com/38703177/72438096-a9fef500-3793-11ea-97c0-cd5d4a04754a.png)

Like this. I'm sure it's the theme's fault but I'd like to be sure before I submit anything to the theme dev.

**Comment by lvitals** [comment]
![Captura de tela de 2020-01-16 21-56-21](https://user-images.githubusercontent.com/2145794/72575622-c55d2380-38ab-11ea-8424-57cd5fca5f38.png)

The extension has been updated today. Regarding the margin issue, I'm using the vanilla theme Adwaita Gnome and I'm not having this issue. It may be that the theme you are using is changing the .music-box class, because I am tweaking this class to get the right margin padding-right: 6px;
